-- 创建 post_views 表
CREATE TABLE IF NOT EXISTS post_views (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT NOT NULL UNIQUE,
    views INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL
);

-- 创建索引以提高查询性能
CREATE INDEX IF NOT EXISTS idx_post_views_slug ON post_views(slug);

-- 启用 Row Level Security (RLS)
ALTER TABLE post_views ENABLE ROW LEVEL SECURITY;

-- 删除已存在的策略（如果有）
DROP POLICY IF EXISTS "Allow public read access" ON post_views;
DROP POLICY IF EXISTS "Allow service role write access" ON post_views;

-- 创建 RLS 策略：只允许所有人读取
CREATE POLICY "Allow public read access" ON post_views
    FOR SELECT USING (true);

-- 创建 RLS 策略：只允许 service role 进行写操作
CREATE POLICY "Allow service role write access" ON post_views
    FOR ALL USING (auth.role() = 'service_role');

-- 注释
COMMENT ON TABLE post_views IS '统计文章阅读量的表';
COMMENT ON COLUMN post_views.slug IS '文章的唯一标识';
COMMENT ON COLUMN post_views.views IS '文章的阅读次数';
